# Generated by Django 4.0 on 2022-01-09 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Telemetry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('latitude', models.DecimalField(decimal_places=8, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=8, max_digits=11)),
                ('altitude', models.FloatField()),
                ('accuracy', models.FloatField()),
                ('altitude_accuracy', models.FloatField()),
                ('speed', models.FloatField(blank=True)),
                ('bearing', models.FloatField(blank=True)),
            ],
        ),
    ]
