# Generated by Django 4.0 on 2022-01-10 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telemetry', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telemetry',
            name='bearing',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='telemetry',
            name='speed',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
