site_name: finitetelemetry
site_description: Server for the FiniteTelemetry App
repo_url: https://github.com/The owner of the repository. Either your github username or organization name./piedpiper-web
site_dir: site
copyright: Copyright &copy; 2020, <a href="https://github.com/The owner of the repository. Either your github username or organization name.">The owner of the repository. Either your github username or organization name.</a>.
dev_addr: 0.0.0.0:8001

nav:
  - Home: 'index.md'
  - API:
    - Authentication: 'api/authentication.md'
    - Users: 'api/users.md'
